/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    abonnes: AbonneAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    podcasts: Podcast;
    videos: Video;
    documents: Document;
    dossiers: Dossier;
    pages: Page;
    media: Media;
    fichiers: Fichier;
    startups: Startup;
    entreprises: Entreprise;
    personnalites: Personnalite;
    'textes-juridiques': TextesJuridique;
    auteurs: Auteur;
    tags: Tag;
    publicites: Publicite;
    newsletter: Newsletter;
    abonnes: Abonne;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    dossiers: DossiersSelect<false> | DossiersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    fichiers: FichiersSelect<false> | FichiersSelect<true>;
    startups: StartupsSelect<false> | StartupsSelect<true>;
    entreprises: EntreprisesSelect<false> | EntreprisesSelect<true>;
    personnalites: PersonnalitesSelect<false> | PersonnalitesSelect<true>;
    'textes-juridiques': TextesJuridiquesSelect<false> | TextesJuridiquesSelect<true>;
    auteurs: AuteursSelect<false> | AuteursSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    publicites: PublicitesSelect<false> | PublicitesSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    abonnes: AbonnesSelect<false> | AbonnesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'ar') | ('fr' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'fr' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Abonne | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AbonneAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Deux ou trois phrases. Sert de résumé sur les listes, dans les partages et comme méta-description par défaut.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  format: 'actualite' | 'analyse' | 'decryptage' | 'interview' | 'tribune' | 'infographie';
  /**
   * Commune aux deux langues. Les rubriques viennent du cahier des charges : ne pas en inventer.
   */
  rubrique:
    | 'economie'
    | 'actus-juridique'
    | 'la-startup-marocaine'
    | 'legaltech-fintech'
    | 'decryptage-sectoriel'
    | 'tendances';
  /**
   * Facultatif. Doit appartenir à la rubrique choisie — sinon l’enregistrement est refusé.
   */
  sousRubrique?:
    | (
        | 'propriete-intellectuelle-numerique'
        | 'droit-des-plateformes'
        | 'droit-confiance-numerique'
        | 'donnees-personnelles'
        | 'creativite-par-le-droit'
        | 'levees-de-fonds'
        | 'classements-par-secteur'
        | 'ecosysteme'
        | 'marche-legaltech'
        | 'actualite-fintech'
        | 'reglementation-numerique'
        | 'encouragement-innovation'
        | 'applis-mobiles'
        | 'plateformes-innovantes'
        | 'formations-organisations'
      )
    | null;
  /**
   * Commune aux deux langues. Une date future ne programme rien pour l’instant : elle ne fait que dater l’article.
   */
  publishedAt?: string | null;
  /**
   * Candidat à la mise en avant sur l’accueil. Le plus récent des articles cochés prend la grande place.
   */
  aLaUne?: boolean | null;
  /**
   * SANS EFFET. Le site est intégralement gratuit ; ce champ est une réserve technique.
   */
  accessLevel?: ('public' | 'metered' | 'premium') | null;
  creePar?: (string | null) | User;
  /**
   * Commune aux deux langues. 1200 × 675 minimum — c’est aussi l’image de partage par défaut.
   */
  coverImage?: (string | null) | Media;
  /**
   * Un ou plusieurs auteurs. Vide = « La rédaction ».
   */
  auteurs?: (string | Auteur)[] | null;
  startups?: (string | Startup)[] | null;
  entreprises?: (string | Entreprise)[] | null;
  personnalites?: (string | Personnalite)[] | null;
  textesJuridiques?: (string | TextesJuridique)[] | null;
  dossiers?: (string | Dossier)[] | null;
  tags?: (string | Tag)[] | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  nom: string;
  role: 'admin' | 'redacteur-en-chef' | 'journaliste' | 'contributeur';
  /**
   * Affichée sur la page auteur si la personne signe des articles.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Obligatoire pour l’accessibilité et le référencement. Décrire l’image, pas la légender.
   */
  alt: string;
  credit?: string | null;
  legende?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auteurs".
 */
export interface Auteur {
  id: string;
  /**
   * Localisé : la version arabe porte le nom en arabe, pas une translittération automatique.
   */
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  fonction?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  email?: string | null;
  linkedin?: string | null;
  x?: string | null;
  /**
   * Facultatif. À renseigner si cet auteur se connecte lui-même au site.
   */
  compte?: (string | null) | User;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Fiche d’entité. La liste d’articles de la page se remplit toute seule à partir des articles qui citent la startup — ne rien lister ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups".
 */
export interface Startup {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  secteur?:
    | (
        | 'fintech'
        | 'legaltech'
        | 'e-commerce'
        | 'healthtech'
        | 'edtech'
        | 'logistique'
        | 'agritech'
        | 'energie'
        | 'ia'
        | 'cybersecurite'
        | 'autre'
      )
    | null;
  stade?: ('idee' | 'amorcage' | 'serie-a' | 'serie-b-plus' | 'rentable' | 'rachetee' | 'cessee') | null;
  anneeCreation?: number | null;
  ville?: string | null;
  siteWeb?: string | null;
  logo?: (string | null) | Media;
  fondateurs?: (string | Personnalite)[] | null;
  /**
   * Une ligne par tour annoncé. Montant en chiffres, sans espace ni symbole.
   */
  levees?:
    | {
        date: string;
        tour: 'pre-seed' | 'seed' | 'serie-a' | 'serie-b' | 'serie-c-plus' | 'dette' | 'subvention' | 'nc';
        /**
         * Laisser vide si non communiqué.
         */
        montant?: number | null;
        devise?: ('MAD' | 'USD' | 'EUR') | null;
        investisseurs?: string | null;
        /**
         * Lien vers l’annonce officielle. Un montant sans source ne se publie pas.
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Fiches publiques de personnes réelles : s’en tenir aux faits professionnels vérifiables et sourcés.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnalites".
 */
export interface Personnalite {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  fonction?: string | null;
  nationalite?: string | null;
  organisation?:
    | ({
        relationTo: 'startups';
        value: string | Startup;
      } | null)
    | ({
        relationTo: 'entreprises';
        value: string | Entreprise;
      } | null);
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (string | null) | Media;
  linkedin?: string | null;
  x?: string | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entreprises".
 */
export interface Entreprise {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  nature?:
    | (
        | 'entreprise'
        | 'banque'
        | 'cabinet'
        | 'administration'
        | 'regulateur'
        | 'federation'
        | 'fonds'
        | 'universite'
        | 'autre'
      )
    | null;
  secteur?: string | null;
  siege?: string | null;
  siteWeb?: string | null;
  logo?: (string | null) | Media;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textes-juridiques".
 */
export interface TextesJuridique {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Numéro seul, tel qu’il est cité : « 09-08 », « 43-20 ». C’est ce que les gens tapent dans Google.
   */
  reference: string;
  typeTexte: 'loi' | 'projet-de-loi' | 'decret' | 'arrete' | 'circulaire' | 'dahir' | 'convention' | 'jurisprudence';
  statut: 'en-vigueur' | 'projet' | 'modifie' | 'abroge';
  /**
   * À remettre à jour à chaque vérification : c’est ce qui rend la fiche fiable.
   */
  dateStatut?: string | null;
  datePublicationBO?: string | null;
  numeroBO?: string | null;
  /**
   * URL du texte sur le site du SGG ou du Bulletin officiel.
   */
  lienOfficiel?: string | null;
  /**
   * Le texte tel que publié. La version arabe et la version française sont deux fichiers distincts.
   */
  fichier?: (string | null) | Fichier;
  /**
   * Résumé de vulgarisation, pas une recopie du texte. C’est le contenu qui fait ranker la page.
   */
  resume?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Texte modifié, décret d’application, texte abrogé…
   */
  textesLies?: (string | TextesJuridique)[] | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Les fichiers téléchargeables. Le titre et la description se saisissent sur la fiche qui les utilise, pas ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fichiers".
 */
export interface Fichier {
  id: string;
  /**
   * Pour la rédaction uniquement : version, provenance, date de mise à jour du fichier.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Les articles s’ajoutent depuis la fiche de l’article, pas depuis ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossiers".
 */
export interface Dossier {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  kicker?: string | null;
  description?: string | null;
  coverImage?: (string | null) | Media;
  /**
   * Décocher quand le sujet est clos : le dossier reste en ligne mais sort des mises en avant.
   */
  enCours?: boolean | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Transversal aux rubriques. Un mot-clé n’est utile que s’il regroupe plusieurs articles dans la durée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Affichée en tête de la page du mot-clé. Deux phrases suffisent.
   */
  description?: string | null;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Ce qui se dit dans l’épisode, avec les liens cités. Indexable — contrairement à l’audio.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL d’intégration fournie par l’hébergeur audio. Ne pas téléverser le MP3 dans la médiathèque.
   */
  embedUrl: string;
  /**
   * Facultatif mais fortement recommandé : accessibilité, et c’est le seul texte que Google peut lire.
   */
  transcription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  numero?: number | null;
  duree?: number | null;
  publishedAt?: string | null;
  coverImage?: (string | null) | Media;
  invites?: (string | Personnalite)[] | null;
  articlesLies?: (string | Article)[] | null;
  tags?: (string | Tag)[] | null;
  creePar?: (string | null) | User;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  /**
   * Deux mots au-dessus du titre : « Décryptage », « Entretien », « En 5 minutes ».
   */
  kicker?: string | null;
  /**
   * Collez l’URL telle quelle : lien de partage, lien watch ou lien d’intégration. Ne pas téléverser le fichier vidéo.
   */
  url: string;
  /**
   * Affichée sur la vignette (8:32).
   */
  duree?: number | null;
  publishedAt?: string | null;
  /**
   * Recommandée en 16:9. À défaut, une image d’attente aux couleurs du journal est affichée — jamais la vignette de la plateforme.
   */
  coverImage?: (string | null) | Media;
  articlesLies?: (string | Article)[] | null;
  tags?: (string | Tag)[] | null;
  creePar?: (string | null) | User;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Deux lignes : ce que contient le document et à qui il sert. C’est le seul texte indexable — le PDF, lui, ne l’est pas.
   */
  description?: string | null;
  /**
   * Décide la section dans laquelle le document apparaît sur la page Documents & modèles.
   */
  categorie: 'contrat' | 'attestation' | 'etude' | 'synthese' | 'autre';
  fichier: string | Fichier;
  publishedAt?: string | null;
  articlesLies?: (string | Article)[] | null;
  tags?: (string | Tag)[] | null;
  creePar?: (string | null) | User;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Laisser vide : généré depuis le titre de CETTE langue. Une fois l’article en ligne, le modifier casse les liens existants.
   */
  slug?: string | null;
  /**
   * Détermine l’URL dans les deux langues. Une seule page par clé.
   */
  cle:
    | 'qui-sommes-nous'
    | 'la-redaction'
    | 'nous-rejoindre'
    | 'nous-contacter'
    | 'newsletter'
    | 'mentions-legales'
    | 'politique-de-confidentialite';
  chapeau?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  creePar?: (string | null) | User;
  /**
   * Facultatif. Vide = le titre et le chapeau de l’article sont utilisés.
   */
  seo?: {
    /**
     * Environ 60 caractères. Au-delà, Google tronque.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
    /**
     * 1200 × 630. Vide = image de couverture, puis image par défaut du site.
     */
    image?: (string | null) | Media;
    /**
     * Retire la page des moteurs de recherche, dans cette langue uniquement.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Un emplacement libre affiche une invitation à réserver l’espace. Rien à supprimer pour « éteindre » une campagne : décochez « Active ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicites".
 */
export interface Publicite {
  id: string;
  /**
   * Le nom réel de l’annonceur : il sert de texte alternatif à l’image, donc il est lu par les lecteurs d’écran.
   */
  annonceur: string;
  /**
   * Le format est imposé par l’emplacement. Fournir l’image à ces dimensions exactes : une image au mauvais rapport sera centrée dans le cadre, pas étirée.
   */
  emplacement: 'header-leaderboard' | 'rail-top' | 'rail-bottom';
  visuel: string | Media;
  /**
   * URL complète, https:// inclus. Le lien est marqué « sponsorisé » pour Google — obligatoire, et cela protège le référencement du journal.
   */
  lienCible: string;
  dateDebut?: string | null;
  /**
   * Laisser vide pour une diffusion sans échéance.
   */
  dateFin?: string | null;
  actif?: boolean | null;
  /**
   * Contact, numéro de bon de commande, montant. Jamais affiché sur le site.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Données personnelles (loi 09-08). Ne pas exporter hors des besoins de la newsletter ; toute désinscription doit être honorée sans délai.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: string;
  email: string;
  prenom?: string | null;
  locale: 'fr' | 'ar';
  statut: 'actif' | 'desinscrit' | 'bounce';
  /**
   * Preuve du consentement explicite (loi 09-08). Ne jamais cocher à la main pour une adresse importée.
   */
  consentement: boolean;
  dateConsentement?: string | null;
  source?: string | null;
  /**
   * Non coché = l’adresse est bien enregistrée ici mais pas encore poussée chez Brevo.
   */
  brevoSynced?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les comptes lecteurs gratuits. Ils n’ont jamais accès à ce tableau de bord.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes".
 */
export interface Abonne {
  id: string;
  /**
   * Facultatif : un lecteur n’est pas obligé de se nommer pour recevoir la newsletter.
   */
  nom?: string | null;
  /**
   * Détermine la langue des envois. Un article sans version dans cette langue n’est pas envoyé (règle d’or #2).
   */
  localePreferee?: ('fr' | 'ar') | null;
  /**
   * Loi 09-08 : le consentement doit être explicite et daté. Ne jamais cocher à la place du lecteur.
   */
  consentementNewsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'abonnes';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'podcasts';
        value: string | Podcast;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'dossiers';
        value: string | Dossier;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'fichiers';
        value: string | Fichier;
      } | null)
    | ({
        relationTo: 'startups';
        value: string | Startup;
      } | null)
    | ({
        relationTo: 'entreprises';
        value: string | Entreprise;
      } | null)
    | ({
        relationTo: 'personnalites';
        value: string | Personnalite;
      } | null)
    | ({
        relationTo: 'textes-juridiques';
        value: string | TextesJuridique;
      } | null)
    | ({
        relationTo: 'auteurs';
        value: string | Auteur;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'publicites';
        value: string | Publicite;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: string | Newsletter;
      } | null)
    | ({
        relationTo: 'abonnes';
        value: string | Abonne;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'abonnes';
        value: string | Abonne;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'abonnes';
        value: string | Abonne;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  format?: T;
  rubrique?: T;
  sousRubrique?: T;
  publishedAt?: T;
  aLaUne?: T;
  accessLevel?: T;
  creePar?: T;
  coverImage?: T;
  auteurs?: T;
  startups?: T;
  entreprises?: T;
  personnalites?: T;
  textesJuridiques?: T;
  dossiers?: T;
  tags?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  embedUrl?: T;
  transcription?: T;
  numero?: T;
  duree?: T;
  publishedAt?: T;
  coverImage?: T;
  invites?: T;
  articlesLies?: T;
  tags?: T;
  creePar?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  kicker?: T;
  url?: T;
  duree?: T;
  publishedAt?: T;
  coverImage?: T;
  articlesLies?: T;
  tags?: T;
  creePar?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  categorie?: T;
  fichier?: T;
  publishedAt?: T;
  articlesLies?: T;
  tags?: T;
  creePar?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dossiers_select".
 */
export interface DossiersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kicker?: T;
  description?: T;
  coverImage?: T;
  enCours?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cle?: T;
  chapeau?: T;
  body?: T;
  creePar?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  legende?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fichiers_select".
 */
export interface FichiersSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups_select".
 */
export interface StartupsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  secteur?: T;
  stade?: T;
  anneeCreation?: T;
  ville?: T;
  siteWeb?: T;
  logo?: T;
  fondateurs?: T;
  levees?:
    | T
    | {
        date?: T;
        tour?: T;
        montant?: T;
        devise?: T;
        investisseurs?: T;
        source?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entreprises_select".
 */
export interface EntreprisesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  nature?: T;
  secteur?: T;
  siege?: T;
  siteWeb?: T;
  logo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnalites_select".
 */
export interface PersonnalitesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  fonction?: T;
  nationalite?: T;
  organisation?: T;
  bio?: T;
  photo?: T;
  linkedin?: T;
  x?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textes-juridiques_select".
 */
export interface TextesJuridiquesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  reference?: T;
  typeTexte?: T;
  statut?: T;
  dateStatut?: T;
  datePublicationBO?: T;
  numeroBO?: T;
  lienOfficiel?: T;
  fichier?: T;
  resume?: T;
  textesLies?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auteurs_select".
 */
export interface AuteursSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  fonction?: T;
  bio?: T;
  photo?: T;
  email?: T;
  linkedin?: T;
  x?: T;
  compte?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicites_select".
 */
export interface PublicitesSelect<T extends boolean = true> {
  annonceur?: T;
  emplacement?: T;
  visuel?: T;
  lienCible?: T;
  dateDebut?: T;
  dateFin?: T;
  actif?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  prenom?: T;
  locale?: T;
  statut?: T;
  consentement?: T;
  dateConsentement?: T;
  source?: T;
  brevoSynced?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes_select".
 */
export interface AbonnesSelect<T extends boolean = true> {
  nom?: T;
  localePreferee?: T;
  consentementNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}